### ISSUE TITLE
How is the tagging of the subnets and security groups taken cared of

### ISSUE THREAD

**Issue by ashishkurian** [aws-samples/cdk-eks-karpenter#144]
Hello There,

I was creating my own cdk stack which migrates my eks cluster from cluster autoscaler to karpenter. I did not find this cdk construct until now.

In my stack, I successfully create everything except, the [tagging](https://karpenter.sh/docs/getting-started/migrating-from-cas/#add-tags-to-subnets-and-security-groups) of the subnets and security groups. Somehow, I am finding it difficult to acheive that. I know an easy solution would be run a boto3 code after I have deployed everything. Instead I would like to see the tagging also done as part of the cdk.

Does this cdk construct take care of the tagging part if I just pass the eks cluster into the construct call?

**Comment by andskli** [comment]
Hi @ashishkurian, this construct is not responsible for tagging subnets, and probably shouldn't be so that it does not modify resources which it does not own. Instead, tagging should sit with the CDK code used for creating the VPC, EKS cluster, etc. As an example, you can see https://github.com/aws-samples/cdk-eks-karpenter/blob/main/test/integ.karpenter.ts, where the `EC2NodeClass` uses up tags from the VPC created in the same stack.
